---
abstract: 'command line utilities for music composition and analysis'
author:
  - 'Jeremy Mates <jmates@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-MusicTools
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  File::Temp: 0
  Getopt::Long: 0
  IPC::Open3: 0
  List::MoreUtils: 0
  List::Util: 0
  Music::AtonalUtil: 0
  Music::Chord::Note: 0
  Music::Chord::Positions: 0
  Music::LilyPondUtil: 0.1
  Music::Tension: 0.6
  Parse::Range: 0
  Scalar::Util: 0
  Text::Roman: 0
  Text::Wrap: 0
resources:
  homepage: http://github.com/thrig/App-MusicTools
  license: http://dev.perl.org/licenses/
  repository: http://github.com/thrig/App-MusicTools
version: 0.52
