--- #YAML:1.0
name:               App-MusicTools
version:            0.80
abstract:           command line utilities for music composition and analysis
author:
    - Jeremy Mates <jmates@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 0
    File::Slurp:          0
    File::Spec:           0
    File::Temp:           0
    Getopt::Long:         0
    IPC::Open3:           0
    List::MoreUtils:      0
    List::Util:           0
    Music::AtonalUtil:    0.7
    Music::Chord::Note:   0
    Music::Chord::Positions:  0
    Music::LilyPondUtil:  0.1
    Music::Tension:       0.6
    Parse::Range:         0
    Scalar::Util:         0
    Test::More:           0
    Text::Roman:          0
    Text::Wrap:           0
resources:
    homepage:    http://github.com/thrig/App-MusicTools
    license:     http://dev.perl.org/licenses/
    repository:  http://github.com/thrig/App-MusicTools
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
